name: Build Sphinx Documentation

on:
  push:
    branches:
      - '**'  # This means any branch
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'  # This enables pip caching
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build Documentation
      run: |
        make html
    
    - name: Upload documentation artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sphinx-docs
        path: _build/html/
        retention-days: 7